- docs/firestore/query.mdx
```js
const query = useFirestoreQuery(["products", { limitTo }], products, {
subscribe: true,
});
```
`query` conflicts with imported query naming, updated to `ref`
> docs: updated typo on query reference naming

- .eslintrc.json
- package.json
- packages/firestore/__test__/helpers.tsx
- packages/firestore/__test__/useFirestoreDocument.test.ts
- packages/firestore/__test__/useFirestoreQuery.test.ts
- packages/firestore/src/index.ts
- packages/firestore/src/useFirestoreDocument.ts
- packages/firestore/src/useFirestoreMutation.ts
- packages/firestore/src/useFirestoreQuery.ts
Allows the support of providing a document id:
```js
useFirestoreDocumentData('', ref, {
idField: 'id',
});
useFirestoreQueryData('', ref, {
idField: 'id',
});
```
TypeScript also supported:
```ts
useFirestoreDocumentData<'id'>('', ref, {
idField: 'id',
});
useFirestoreQueryData<'id'>('', ref, {
idField: 'id',
});
```
> feat(firestore): support idField args

- packages/analytics/package.json
- packages/auth/package.json
- packages/database/package.json
- packages/firestore/package.json
- packages/functions/package.json
Sync peer deps with react-query. 
Now we can use React ^16.8 as well.
> Sync peer deps with react-query

- docs.json
The "Authentication State" section was missing from the docs navigation sidebar, so I've added it there.
> Add nav link to missing auth section

- packages/utils/src/useSubscription.ts
Fixes https://github.com/invertase/react-query-firebase/issues/25#issuecomment-1179769240
React-query-firebase was managing it's own observerCount, but it was incorrect. React-query already does this and is was correct.
When there are no observers firestore is unsubscribed. If there are observers it is added again.
Also improved the readability of the code a bit by using more variables / helper functions.
Verified it is working in my application that was having issues.
I had some trouble running the tests.
> Let react-query manage observer count

- vitest.config.ts
Tests currently fail due to vitest failing to resolve the path of `~/testing-util`. Vitest seems not to automatically know how to resolve the alias. This PR introduces an `alias` key to the vitest config so as to explicitly configure vitest to resolve the path to the alias.
> Fix vitest aliases configuration

- packages/react/src/firestore/index.ts
- packages/react/src/firestore/useDocumentQuery.test.tsx
- packages/react/src/firestore/useDocumentQuery.ts
- packages/react/src/firestore/useFirestoreDocument.test.tsx
- vitest/utils.ts
This PR tests the `useDocumentQuery` hook for the following assertions;
- fetches document from server source
- handles fetch errors
- returns pending state initially
- returns correct data type
> rename and add tests to useDocumentQuery

- package.json
- packages/react/src/auth/useSignInAnonymouslyMutation.test.tsx
- vitest/utils.ts
this pr adds tests to `useSignInAnonymouslyMutation` hook
> Add tests for useSignInAnonymouslyMutation hook

- packages/react/src/firestore/index.ts
- packages/react/src/firestore/useWaitForPendingWritesQuery.test.tsx
- packages/react/src/firestore/useWaitForPendingWritesQuery.ts
This PR adds `useWaitForPendingWritesQuery`
> Add useWaitForPendingWritesQuery

- packages/react/src/firestore/index.ts
- packages/react/src/firestore/useDisableNetworkMutation.test.tsx
- packages/react/src/firestore/useDisableNetworkMutation.ts
This PR adds `useDisableNetworkMutation`
> Add useDisableNetworkMutation

- package.json
- packages/react/src/auth/index.ts
- packages/react/src/auth/useSignInWithCredentialMutation.test.tsx
- packages/react/src/auth/useSignInWithCredentialMutation.ts
- pnpm-lock.yaml
- vitest/utils.ts
this PR adds useSignInWithCredentialMutation hook
> Add useSignInWithCredentialMutation

- packages/react/src/auth/index.ts
- packages/react/src/auth/useSignInWithEmailAndPasswordMutation.test.tsx
- packages/react/src/auth/useSignInWithEmailAndPasswordMutation.ts
This PR adds `useSignInWithEmailAndPasswordMutation` hook.
> feat: add useSignInWithEmailAndPasswordMutation hook

- packages/react/src/auth/index.ts
- packages/react/src/auth/useSignOutMutation.test.tsx
- packages/react/src/auth/useSignOutMutation.ts
This PR adds `useSignOutMutation` hook;
> feat: add useSignOutMutation hook

- .github/workflows/tests.yaml
- .gitignore
- packages/react/src/firestore/useClearIndexedDbPersistenceMutation.ts
- vitest.config.ts
- Disable running test files in parallel to solve race conditions
- Upgrade `invertase/firebase-emulator-action` to v1.0.1
> fix: tests

- packages/react/src/firestore/index.ts
This PR removes `useEnableIndexedDbPersistenceMutation` as the API is now obsolete.
> chore(react/firestore): remove obsolete useEnableIndexedDbPersistenceMutation

- packages/react/src/auth/index.ts
- packages/react/src/auth/useGetRedirectResultQuery.test.tsx
- packages/react/src/auth/useGetRedirectResultQuery.ts
This pr adds useGetRedirectResultQuery.
> feat(react/auth): add useGetRedirectResultQuery

- packages/react/src/auth/index.ts
This pr removes `useFetchSignInMethodsForEmailQuery` as `fetchSignInMethodsForEmail` has got some deprecated parts.
> chore(react/auth): remove useFetchSignInMethodsForEmailQuery

- packages/react/src/firestore/index.ts
- packages/react/src/firestore/useDeleteDocumentMutation.test.tsx
- packages/react/src/firestore/useDeleteDocumentMutation.ts
Adds useDeleteDocumentMutation hook.
> feat(react/firestore): add useDeleteDocumentMutation

- packages/react/package.json
- packages/react/tsup.config.ts
In `tsconfig.json`, when `moduleResolution` is set to `node`, then the `exports` field is ignored, and instead resolution happens based on paths relative to the root `package.json`. For example, if `@tanstack-query-firebase/react` is imported from, then like normal, the package.json in the root of the package is referenced. Then, if the user has a subpath import, such as `@tanstack-query-firebase/react/data-connect`, then, as the node module resolution doesn't understand the exports field, looks for types at the `data-connect` folder, relative to the root package.json. This PR allows users to use the `node` module resolution and any future ones that respect the `exports` field as well.
**Note: This requires publishing from the `dist` folder, so the `publish-package` script was copied over …
> Fixed issue where node module resolution wasn't being respected

- dataconnect-sdk/js/default-connector/README.md
- dataconnect-sdk/js/default-connector/index.cjs.js
- packages/react/package.json
- packages/react/src/data-connect/useDataConnectQuery.test.tsx
- packages/react/src/data-connect/useDataConnectQuery.ts
- packages/react/src/data-connect/utils.test.ts
- packages/react/src/data-connect/utils.ts
- pnpm-lock.yaml
supercedes https://github.com/invertase/tanstack-query-firebase/pull/180 - rebased to resolve conflicts
> fix: ensure updated variables get picked up (rebase)
